// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportService.Infrastructure;

#nullable disable

namespace ReportService.Infrastructure.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260515175649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReportService.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AnalysisProcessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisProcessId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ReportService.Domain.Report", b =>
                {
                    b.OwnsOne("ReportService.Domain.AiModelMetadata", "AiModelMetadata", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Confidence")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PromptVersion")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ReportId");

                            b1.ToTable("Reports");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsMany("ReportService.Domain.ReportComponent", "Components", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ReportId", "Id");

                            b1.ToTable("ReportComponent");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsMany("ReportService.Domain.ReportRecommendation", "Recommendations", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ReportId", "Id");

                            b1.ToTable("ReportRecommendation");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsMany("ReportService.Domain.ReportRisk", "Risks", b1 =>
                        {
                            b1.Property<Guid>("ReportId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Recommendation")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Severity")
                                .HasColumnType("int");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ReportId", "Id");

                            b1.ToTable("ReportRisk");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.Navigation("AiModelMetadata");

                    b.Navigation("Components");

                    b.Navigation("Recommendations");

                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
